---
AWSTemplateFormatVersion: '2010-09-09'
Description: Stack providing cross account access for GuardDutyRecruiter
# Name : guarddutyrecruiter-organizations-role

Parameters:

  GuardDutyRecruiterCentralAccount:
    Description: AWS account ID where GuardDutyRecruiter is installed
    Type: String
    ConstraintDescription: Must be a valid AWS account ID

  GuardDutyRecruiterOrgRoleExternalId:
    Description: GuardDutyRecruiter Role ExternalID
    Type: String

  GuardDutyRecruiterStackSetSpokeName:
    Description: Name of the StackSet in charge of distributing spoke account assets
    Type: String
    Default: guarddutyrecruiter-spoke-account

Resources:

  GuardDutyRecruiterOrgRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: guarddutyrecruiter-organizations-role
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws:iam::${GuardDutyRecruiterCentralAccount}:root'
          Action:
          - sts:AssumeRole
          Condition:
            StringEquals:
              "sts:ExternalId": !Sub '${GuardDutyRecruiterOrgRoleExternalId}'
      Policies:
      - PolicyName: "AllowOrganizationListAccounts"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action: organizations:ListAccounts
            Resource: '*'
      - PolicyName: "AllowUpdateStackInstances"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
            - cloudformation:CreateStackInstances
            - cloudformation:ListStackInstances
            Resource: !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stackset/${GuardDutyRecruiterStackSetSpokeName}:*"
